fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    limits: https://github.com/erwbgy/puppet-limits.git
    ntp: https://github.com/erwbgy/puppet-ntp.git
    cron_core: https://github.com/puppetlabs/puppetlabs-cron_core.git
    augeasproviders: https://github.com/hercules-team/augeasproviders_core.git
